import { ChainType } from '@lifi/sdk'
import { Chain, ChainId, CrossSwapPlatform } from '../types/cross_swap'

export const supportChainLifiList: Chain[] = [
  {
    name_id: 'sui',
    chain_name: 'Sui',
    type: ChainType.MVM,
    id: ChainId.SUI_LI_FI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sui.svg',
    rpc_urls: ['https://fullnode.mainnet.sui.io:443'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://suivision.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI',
      symbol: 'SUI',
      decimals: 9,
      name: 'SUI',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/20947.png',
    },
  },
  {
    name_id: 'ethereum',
    chain_name: 'Ethereum',
    type: ChainType.EVM,
    id: ChainId.ETH,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ethereum.svg',
    rpc_urls: ['https://ethereum-rpc.publicnode.com', 'https://eth.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://etherscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'solana',
    chain_name: 'Solana',
    type: ChainType.SVM,
    id: ChainId.SOL_LI_FI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/solana.svg',
    rpc_urls: ['https://api.mainnet-beta.solana.com', 'https://solana-rpc.publicnode.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://solana.fm/',
    native_token: {
      address: '11111111111111111111111111111111',
      symbol: 'SOL',
      decimals: 9,
      name: 'SOL',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
    },
  },
  {
    name_id: 'bsc',
    chain_name: 'BSC',
    type: ChainType.EVM,
    id: ChainId.BSC,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bsc.svg',
    rpc_urls: [
      'https://bsc-dataseed.binance.org',
      'https://bsc-dataseed.bnbchain.org',
      'https://bsc-rpc.publicnode.com',
      'https://bsc-dataseed1.defibit.io',
      'https://bsc-dataseed1.ninicoin.io',
    ],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://bscscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'BNB',
      decimals: 18,
      name: 'BNB',
      logo_url: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
    },
  },
  {
    name_id: 'arbitrum',
    chain_name: 'Arbitrum',
    type: ChainType.EVM,
    id: ChainId.ARB,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/arbitrum.svg',
    rpc_urls: ['https://arb1.arbitrum.io/rpc', 'https://arbitrum-one-rpc.publicnode.com', 'https://arbitrum.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://arbiscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'base',
    chain_name: 'Base',
    type: ChainType.EVM,
    id: ChainId.BAS,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/base.svg',
    rpc_urls: ['https://mainnet.base.org', 'https://base-rpc.publicnode.com', 'https://base.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://basescan.org/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'bls',
    chain_name: 'Blast',
    type: ChainType.EVM,
    id: ChainId.BLS,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/blast.svg',
    rpc_urls: ['https://rpc.blast.io', 'https://blast-rpc.publicnode.com', 'https://blast.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://blastscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'ava',
    chain_name: 'Avalanche',
    type: ChainType.EVM,
    id: ChainId.AVA,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/avalanche.svg',
    rpc_urls: ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche-c-chain-rpc.publicnode.com', 'https://avalanche.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://snowtrace.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'AVAX',
      decimals: 18,
      name: 'AVAX',
      logo_url: 'https://static.debank.com/image/avax_token/logo_url/avax/0b9c84359c84d6bdd5bfda9c2d4c4a82.png',
    },
  },
  {
    name_id: 'pol',
    chain_name: 'Polygon',
    type: ChainType.EVM,
    id: ChainId.POL,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/polygon.svg',
    rpc_urls: ['https://polygon-bor-rpc.publicnode.com', 'https://polygon.drpc.org', 'https://polygon-rpc.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://polygonscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'POL',
      decimals: 18,
      name: 'Polygon Ecosystem Token',
      logo_url: 'https://static.debank.com/image/matic_token/logo_url/matic/6f5a6b6f0732a7a235131bd7804d357c.png',
    },
  },
  {
    name_id: 'scl',
    chain_name: 'Scroll',
    type: ChainType.EVM,
    id: ChainId.SCL,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/scroll.svg',
    rpc_urls: ['https://rpc.scroll.io', 'https://scroll.drpc.org', 'https://scroll-mainnet.public.blastapi.io', 'https://1rpc.io/scroll'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://scrollscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'opt',
    chain_name: 'Optimism',
    type: ChainType.EVM,
    id: ChainId.OPT,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/optimism.svg',
    rpc_urls: ['https://mainnet.optimism.io/', 'https://optimism-rpc.publicnode.com', 'https://optimism.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://optimistic.etherscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'lna',
    chain_name: 'Linea',
    type: ChainType.EVM,
    id: ChainId.LNA,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/linea.svg',
    rpc_urls: ['https://rpc.linea.build'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://lineascan.build/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'era',
    chain_name: 'zkSync',
    type: ChainType.EVM,
    id: ChainId.ERA,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/zksync.svg',
    rpc_urls: ['https://mainnet.era.zksync.io'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.zksync.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'pze',
    chain_name: 'Polygon zkEVM',
    type: ChainType.EVM,
    id: ChainId.PZE,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/zkevm.svg',
    rpc_urls: ['https://zkevm-rpc.com', 'https://polygon-zkevm.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://zkevm.polygonscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'dai',
    chain_name: 'Gnosis',
    type: ChainType.EVM,
    id: ChainId.DAI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/gnosis.svg',
    rpc_urls: ['https://rpc.gnosischain.com', 'https://gnosis-rpc.publicnode.com', 'https://gnosis.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://gnosis.blockscout.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'xDAI',
      decimals: 18,
      name: 'xDAI Native Token',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png',
    },
  },
  {
    name_id: 'ftm',
    chain_name: 'Fantom',
    type: ChainType.EVM,
    id: ChainId.FTM,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fantom.svg',
    rpc_urls: [
      'https://rpcapi.fantom.network',
      'https://rpc.fantom.network',
      'https://fantom-rpc.publicnode.com',
      'https://fantom.drpc.org',
    ],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://ftmscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'FTM',
      decimals: 18,
      name: 'FTM',
      logo_url: 'https://static.debank.com/image/ftm_token/logo_url/ftm/33fdb9c5067e94f3a1b9e78f6fa86984.png',
    },
  },
  {
    name_id: 'mor',
    chain_name: 'Moonriver',
    type: ChainType.EVM,
    id: ChainId.MOR,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/moonriver.svg',
    rpc_urls: ['https://rpc.api.moonriver.moonbeam.network', 'https://moonriver-rpc.publicnode.com', 'https://moonriver.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://moonriver.moonscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'MOVR',
      decimals: 18,
      name: 'MOVR',
      logo_url: 'https://assets.coingecko.com/coins/images/17984/small/9285.png',
    },
  },
  {
    name_id: 'moo',
    chain_name: 'Moonbeam',
    type: ChainType.EVM,
    id: ChainId.MOO,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/moonbeam.svg',
    rpc_urls: ['https://rpc.api.moonbeam.network', 'https://moonbeam-rpc.publicnode.com', 'https://moonbeam.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://moonbeam.moonscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'GLMR',
      decimals: 18,
      name: 'GLMR',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/6836.png',
    },
  },
  {
    name_id: 'fus',
    chain_name: 'FUSE',
    type: ChainType.EVM,
    id: ChainId.FUS,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fuse.svg',
    rpc_urls: ['https://rpc.fuse.io', 'https://fuse.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.fuse.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'FUSE',
      decimals: 18,
      name: 'FUSE',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5634.png',
    },
  },
  {
    name_id: 'bob',
    chain_name: 'Boba',
    type: ChainType.EVM,
    id: ChainId.BOB,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/boba.svg',
    rpc_urls: ['https://mainnet.boba.network', 'https://replica.boba.network'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://bobascan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'mod',
    chain_name: 'Mode',
    type: ChainType.EVM,
    id: ChainId.MOD,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/mode.svg',
    rpc_urls: ['https://mainnet.mode.network', 'https://mode.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.mode.network/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'mam',
    chain_name: 'Metis',
    type: ChainType.EVM,
    id: ChainId.MAM,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/metis.svg',
    rpc_urls: ['https://andromeda.metis.io', 'https://metis.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://andromeda-explorer.metis.io/',
    native_token: {
      address: '0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000',
      symbol: 'METIS',
      decimals: 18,
      name: 'METIS',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/9640.png',
    },
  },
  {
    name_id: 'lsk',
    chain_name: 'Lisk',
    type: ChainType.EVM,
    id: ChainId.LSK,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/lisk.svg',
    rpc_urls: ['https://rpc.api.lisk.com', 'https://lisk.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://blockscout.lisk.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'uni',
    chain_name: 'Unichain',
    type: ChainType.EVM,
    id: ChainId.UNI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/unichain.svg',
    rpc_urls: ['https://mainnet.unichain.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://unichain.blockscout.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'aur',
    chain_name: 'Aurora',
    type: ChainType.EVM,
    id: ChainId.AUR,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/aurora.svg',
    rpc_urls: ['https://mainnet.aurora.dev'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.aurora.dev/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'AETH',
      decimals: 18,
      name: 'AETH',
      logo_url: 'https://static.debank.com/image/aurora_token/logo_url/aurora/d61441782d4a08a7479d54aea211679e.png',
    },
  },
  {
    name_id: 'sei',
    chain_name: 'Sei',
    type: ChainType.EVM,
    id: ChainId.SEI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sei.svg',
    rpc_urls: ['https://evm-rpc.sei-apis.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://seitrace.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'SEI',
      decimals: 18,
      name: 'SEI',
      logo_url: 'https://cdn.sei.io/sei-app/sei-icon.png',
    },
  },
  {
    name_id: 'imx',
    chain_name: 'Immutable zkEVM',
    type: ChainType.EVM,
    id: ChainId.IMX,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/imx.svg',
    rpc_urls: ['https://rpc.immutable.com/', 'https://immutable-zkevm.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://immutable-mainnet.blockscout.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'IMX',
      decimals: 18,
      name: 'IMX',
      logo_url:
        'https://static.debank.com/image/eth_token/logo_url/0xf57e7e7c23978c3caec3c3548e3d615c346e79ff/7a875818146ec0508d3e5f5b14f1b4eb.png',
    },
  },
  {
    name_id: 'son',
    chain_name: 'Sonic',
    type: ChainType.EVM,
    id: ChainId.SON,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sonic.svg',
    rpc_urls: ['https://rpc.soniclabs.com', 'https://sonic.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.soniclabs.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'S',
      decimals: 18,
      name: 'S',
      logo_url:
        'https://static.debank.com/image/sonic_token/logo_url/0x039e2fb66102314ce7b64ce5ce3e5183bc94ad38/b4cc70d040518a88adac18d906fcbfff.png',
    },
  },
  {
    name_id: 'gra',
    chain_name: 'Gravity',
    type: ChainType.EVM,
    id: ChainId.GRA,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/gravity.svg',
    rpc_urls: ['https://rpc.gravity.xyz/'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.gravity.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'G',
      decimals: 18,
      name: 'G',
      logo_url: 'https://assets.gravity.xyz/token_logo.png',
    },
  },
  {
    name_id: 'tai',
    chain_name: 'Taiko',
    type: ChainType.EVM,
    id: ChainId.TAI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/taiko.svg',
    rpc_urls: ['https://rpc.mainnet.taiko.xyz', 'https://rpc.taiko.xyz', 'https://rpc.taiko.tools'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://taikoscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'soe',
    chain_name: 'Soneium',
    type: ChainType.EVM,
    id: ChainId.SOE,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/soneium.svg',
    rpc_urls: ['https://rpc.soneium.org/'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://soneium.blockscout.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'swl',
    chain_name: 'Swellchain',
    type: ChainType.EVM,
    id: ChainId.SWL,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/swell.svg',
    rpc_urls: ['https://swell-mainnet.alt.technology'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://swellchainscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'btc',
    chain_name: 'Bitcoin',
    type: ChainType.UTXO,
    id: ChainId.BTC,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bitcoin.svg',
    rpc_urls: ['https://node-router.thorswap.net/bitcoin', 'https://bitcoin-rpc.publicnode.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://mempool.space/',
    native_token: {
      address: 'bitcoin',
      symbol: 'BTC',
      decimals: 8,
      name: 'Bitcoin',
      logo_url: 'https://assets.coingecko.com/coins/images/1/standard/bitcoin.png',
    },
  },
  {
    name_id: 'opb',
    chain_name: 'opBNB',
    type: ChainType.EVM,
    id: ChainId.OPB,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/opbnb.svg',
    rpc_urls: ['https://opbnb-mainnet-rpc.bnbchain.org', 'https://1rpc.io/opbnb'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://opbnb.bscscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'BNB',
      decimals: 18,
      name: 'BNB',
      logo_url: 'https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615',
    },
  },
  {
    name_id: 'crn',
    chain_name: 'Corn',
    type: ChainType.EVM,
    id: ChainId.CRN,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/corn.svg',
    rpc_urls: ['https://mainnet.corn-rpc.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://cornscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'BTCN',
      decimals: 18,
      name: 'Bitcorn',
      logo_url: 'https://static.debank.com/image/corn_token/logo_url/corn/fe230e468272b84aba78d08bb4140456.png',
    },
  },
  {
    name_id: 'lns',
    chain_name: 'Lens',
    type: ChainType.EVM,
    id: ChainId.LNS,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/lens.svg',
    rpc_urls: ['https://api.lens.matterhosted.dev'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.lens.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'GHO',
      decimals: 18,
      name: 'GHO',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/23508.png',
    },
  },
  {
    name_id: 'cro',
    chain_name: 'Cronos',
    type: ChainType.EVM,
    id: ChainId.CRO,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/cronos.svg',
    rpc_urls: ['https://evm.cronos.org', 'https://cronos.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.cronos.org/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'CRO',
      decimals: 18,
      name: 'CRO',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png',
    },
  },
  {
    name_id: 'abs',
    chain_name: 'Abstract',
    type: ChainType.EVM,
    id: ChainId.ABS,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/abstract.svg',
    rpc_urls: ['https://api.mainnet.abs.xyz'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://abscan.org/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'rsk',
    chain_name: 'Rootstock',
    type: ChainType.EVM,
    id: ChainId.RSK,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/rootstock.svg',
    rpc_urls: ['https://public-node.rsk.co', 'https://mycrypto.rsk.co'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.rootstock.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'RBTC',
      decimals: 18,
      name: 'Rootstock Smart Bitcoin',
      logo_url:
        'https://static.debank.com/image/rsk_token/logo_url/0x542fda317318ebf1d3deaf76e0b632741a7e677d/4785a26ef5bb5df987e67ad49fc62137.png',
    },
  },
  {
    name_id: 'ape',
    chain_name: 'Apechain',
    type: ChainType.EVM,
    id: ChainId.APE,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/apechain.svg',
    rpc_urls: ['https://rpc.apechain.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://apescan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'APE',
      decimals: 18,
      name: 'APE',
      logo_url: 'https://static.debank.com/image/ape_token/logo_url/ape/2357165eac1453c46f526704b51a801b.png',
    },
  },
  {
    name_id: 'cel',
    chain_name: 'Celo',
    type: ChainType.EVM,
    id: ChainId.CEL,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/celo.svg',
    rpc_urls: ['https://forno.celo.org', 'https://celo.drpc.org'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://celoscan.io/',
    native_token: {
      address: '0x471EcE3750Da237f93B8E339c536989b8978a438',
      symbol: 'CELO',
      decimals: 18,
      name: 'Celo native asset',
      logo_url: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5567.png',
    },
  },
  {
    name_id: 'wcc',
    chain_name: 'World Chain',
    type: ChainType.EVM,
    id: ChainId.WCC,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/world.svg',
    rpc_urls: ['https://worldchain-mainnet.g.alchemy.com/public', 'https://worldchain-mainnet.gateway.tenderly.co'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://worldscan.org/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'xdc',
    chain_name: 'XDC',
    type: ChainType.EVM,
    id: ChainId.XDC,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/xdc.svg',
    rpc_urls: ['https://erpc.xinfin.network'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://xdcscan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'XDC',
      decimals: 18,
      name: 'XDC',
      logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/xdc.svg',
    },
  },
  {
    name_id: 'mnt',
    chain_name: 'Mantle',
    type: ChainType.EVM,
    id: ChainId.MNT,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/mantle.svg',
    rpc_urls: ['https://rpc.mantle.xyz', 'https://mantle-rpc.publicnode.com', 'https://mantle.drpc.org', 'https://mantle.public-rpc.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.mantle.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'MNT',
      decimals: 18,
      name: 'MNT',
      logo_url:
        'https://static.debank.com/image/mnt_token/logo_url/0x78c1b0c915c4faa5fffa6cabf0219da63d7f4cb8/a443c78c33704d48f06e5686bb87f85e.png',
    },
  },
  {
    name_id: 'sup',
    chain_name: 'Superposition',
    type: ChainType.EVM,
    id: ChainId.SUP,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/superposition.svg',
    rpc_urls: ['https://rpc.superposition.so'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.superposition.so/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'ink',
    chain_name: 'Ink',
    type: ChainType.EVM,
    id: ChainId.INK,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ink.svg',
    rpc_urls: ['https://rpc-gel.inkonchain.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.inkonchain.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'boc',
    chain_name: 'BOB',
    type: ChainType.EVM,
    id: ChainId.BOC,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bob.svg',
    rpc_urls: ['https://rpc.gobob.xyz'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://explorer.gobob.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
  },
  {
    name_id: 'ber',
    chain_name: 'Berachain',
    type: ChainType.EVM,
    id: ChainId.BER,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bera.svg',
    rpc_urls: ['https://rpc.berachain.com'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://berascan.com/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'BERA',
      decimals: 18,
      name: 'BERA',
      logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/tokens/bera.svg',
    },
  },
  {
    name_id: 'kai',
    chain_name: 'Kaia',
    type: ChainType.EVM,
    id: ChainId.KAI,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/kaia.svg',
    rpc_urls: ['https://public-en.node.kaia.io', 'https://klaytn-pokt.nodies.app'],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://kaiascan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'KLAY',
      decimals: 18,
      name: 'KLAY',
      logo_url:
        'https://static.debank.com/image/klay_token/logo_url/0x19aac5f612f524b754ca7e7c41cbfa2e981a4432/1866fc790849a903e0594ce0f55b758d.png',
    },
  },

  {
    name_id: 'hyp',
    chain_name: 'HyperEVM',
    type: ChainType.EVM,
    id: ChainId.HYP,
    logo_url: 'https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/hyperevm.svg',
    rpc_urls: [
      'https://rpc.hyperliquid.xyz/evm',
      'https://rpc.hyperlend.finance',
      'https://hyperliquid-json-rpc.stakely.io',
      'https://hyperliquid.drpc.org',
      'https://rpc.hypurrscan.io',
    ],
    platform: CrossSwapPlatform.LI_FI,
    block_explorer: 'https://www.hyperscan.com//',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'HYPE',
      decimals: 18,
      name: 'HYPE',
      logo_url: 'https://static.debank.com/image/hyper_token/logo_url/hyper/0b3e288cfe418e9ce69eef4c96374583.png',
    },
  },
]
