import { ChainType } from '@lifi/sdk'
import { Chain, ChainId, CrossSwapPlatform } from '../types/cross_swap'

export const supportChainMayanList: Chain[] = [
  {
    name_id: 'sui',
    chain_name: 'Sui',
    type: ChainType.MVM,
    id: ChainId.SUI_MAYAN,
    logo_url: 'https://cdn.mayan.finance/SUI.png',
    rpc_urls: [
      'https://rpc.ankr.com/sui_mainnet',
      'https://rpc.ankr.com/sui/7f818a1013bdbf7c09af32622331588476299eed5149cd6fb944251fe407b87e',
    ],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://suiscan.xyz/mainnet/',
    native_token: {
      address: '0x2::sui::SUI',
      symbol: 'SUI',
      decimals: 9,
      name: 'SUI',
      logo_url: 'https://cdn.mayan.finance/sui_coin.png',
    },
  },
  {
    name_id: 'ethereum',
    chain_name: 'Ethereum',
    type: ChainType.EVM,
    id: ChainId.ETH,
    logo_url: 'https://statics.mayan.finance/assets/eth.png',
    rpc_urls: ['https://eth-mainnet.public.blastapi.io/'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://etherscan.io',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/assets/eth.png',
    },
  },
  {
    name_id: 'solana',
    chain_name: 'Solana',
    type: ChainType.SVM,
    id: ChainId.SOL_MAYAN,
    logo_url: 'https://statics.mayan.finance/assets/SOL.png',
    rpc_urls: [
      'https://rpc.hellomoon.io/34d462f9-1e8e-45b0-a83d-c3c43981ede0',
      'https://proud-fabled-dawn.solana-mainnet.quiknode.pro/06df0fdd93842b3340129b8cdc4af06947fe730d/',
    ],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://explorer.solana.com/',
    native_token: {
      address: 'So11111111111111111111111111111111111111112',
      symbol: 'SOL',
      decimals: 9,
      name: 'SOL',
      logo_url: 'https://statics.mayan.finance/assets/SOL.png',
    },
  },

  {
    name_id: 'base',
    chain_name: 'Base',
    type: ChainType.EVM,
    id: ChainId.BAS,
    logo_url: 'https://cdn.mayan.finance/base.png',
    rpc_urls: ['https://base.llamarpc.com'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://basescan.org/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/assets/eth.png',
    },
  },
  {
    name_id: 'arbitrum',
    chain_name: 'Arbitrum',
    type: ChainType.EVM,
    id: ChainId.ARB,
    logo_url: 'https://cdn.mayan.finance/arbitrum-logo.png',
    rpc_urls: ['https://arb1.arbitrum.io/rpc'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://arbiscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/eth.png',
    },
  },
  {
    name_id: 'optimism',
    chain_name: 'Optimism',
    type: ChainType.EVM,
    id: ChainId.OPT,
    logo_url: 'https://cdn.mayan.finance/optimism.png',
    rpc_urls: ['https://optimism-mainnet.public.blastapi.io'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://optimistic.etherscan.io/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/assets/eth.png',
    },
  },
  {
    name_id: 'polygon',
    chain_name: 'Polygon',
    type: ChainType.EVM,
    id: ChainId.POL,
    logo_url: 'https://statics.mayan.finance/assets/polygon.png',
    rpc_urls: ['https://polygon-bor-rpc.publicnode.com'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://polygonscan.com',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'POL',
      decimals: 18,
      name: 'POL',
      logo_url: 'https://statics.mayan.finance/assets/polygon.png',
    },
  },
  {
    name_id: 'avalanche',
    chain_name: 'Avalanche',
    type: ChainType.EVM,
    id: ChainId.AVA,
    logo_url: 'https://statics.mayan.finance/assets/avax-icon.png',
    rpc_urls: ['https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://snowtrace.io',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'AVAX',
      decimals: 18,
      name: 'Avax',
      logo_url: 'https://statics.mayan.finance/assets/avax-icon.png',
    },
  },
  {
    name_id: 'bsc',
    chain_name: 'BSC',
    type: ChainType.EVM,
    id: ChainId.BSC,
    logo_url: 'https://statics.mayan.finance/assets/bsc.png',
    rpc_urls: ['https://bsc-dataseed1.defibit.io'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://bscscan.com',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'BNB',
      decimals: 18,
      name: 'BNB',
      logo_url: 'https://statics.mayan.finance/assets/bsc.png',
    },
  },

  {
    name_id: 'unichain',
    chain_name: 'Unichain',
    type: ChainType.EVM,
    id: ChainId.UNI,
    logo_url: 'https://cdn.mayan.finance/unichain.png',
    rpc_urls: ['https://unichain-rpc.publicnode.com'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://uniscan.xyz/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/assets/eth.png',
    },
  },
  {
    name_id: 'linea',
    chain_name: 'Linea',
    type: ChainType.EVM,
    id: ChainId.LNA,
    logo_url: 'https://cdn.mayan.finance/linea.png',
    rpc_urls: ['https://linea-rpc.publicnode.com'],
    platform: CrossSwapPlatform.MAYAN,
    block_explorer: 'https://lineascan.build/',
    native_token: {
      address: '0x0000000000000000000000000000000000000000',
      symbol: 'ETH',
      decimals: 18,
      name: 'ETH',
      logo_url: 'https://statics.mayan.finance/assets/eth.png',
    },
  },
]
